// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: Sleepy.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Device struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReportInterval uint64                 `protobuf:"varint,1,opt,name=report_interval,json=reportInterval,proto3" json:"report_interval,omitempty"`
	DeviceType     []string               `protobuf:"bytes,2,rep,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	DevicePlatform string                 `protobuf:"bytes,3,opt,name=device_platform,json=devicePlatform,proto3" json:"device_platform,omitempty"`
	DeviceName     string                 `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_Sleepy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_Sleepy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_Sleepy_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetReportInterval() uint64 {
	if x != nil {
		return x.ReportInterval
	}
	return 0
}

func (x *Device) GetDeviceType() []string {
	if x != nil {
		return x.DeviceType
	}
	return nil
}

func (x *Device) GetDevicePlatform() string {
	if x != nil {
		return x.DevicePlatform
	}
	return ""
}

func (x *Device) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Session       string                 `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_Sleepy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Sleepy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_Sleepy_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegisterResponse) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *RegisterResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Using         bool                   `protobuf:"varint,1,opt,name=using,proto3" json:"using,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_Sleepy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_Sleepy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_Sleepy_proto_rawDescGZIP(), []int{2}
}

func (x *State) GetUsing() bool {
	if x != nil {
		return x.Using
	}
	return false
}

func (x *State) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_Sleepy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_Sleepy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_Sleepy_proto_rawDescGZIP(), []int{3}
}

var File_Sleepy_proto protoreflect.FileDescriptor

const file_Sleepy_proto_rawDesc = "" +
	"\n" +
	"\fSleepy.proto\x12\x05proto\"\x9c\x01\n" +
	"\x06Device\x12'\n" +
	"\x0freport_interval\x18\x01 \x01(\x04R\x0ereportInterval\x12\x1f\n" +
	"\vdevice_type\x18\x02 \x03(\tR\n" +
	"deviceType\x12'\n" +
	"\x0fdevice_platform\x18\x03 \x01(\tR\x0edevicePlatform\x12\x1f\n" +
	"\vdevice_name\x18\x04 \x01(\tR\n" +
	"deviceName\"N\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asession\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"8\n" +
	"\x05State\x12\x14\n" +
	"\x05using\x18\x01 \x01(\bR\x05using\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\"\a\n" +
	"\x05Empty2\xa3\x01\n" +
	"\x06Sleepy\x12:\n" +
	"\x0eRegisterDevice\x12\r.proto.Device\x1a\x17.proto.RegisterResponse\"\x00\x12*\n" +
	"\n" +
	"Unregister\x12\f.proto.Empty\x1a\f.proto.Empty\"\x00\x121\n" +
	"\x11ReportDeviceState\x12\f.proto.State\x1a\f.proto.Empty\"\x00B\tZ\a./protob\x06proto3"

var (
	file_Sleepy_proto_rawDescOnce sync.Once
	file_Sleepy_proto_rawDescData []byte
)

func file_Sleepy_proto_rawDescGZIP() []byte {
	file_Sleepy_proto_rawDescOnce.Do(func() {
		file_Sleepy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Sleepy_proto_rawDesc), len(file_Sleepy_proto_rawDesc)))
	})
	return file_Sleepy_proto_rawDescData
}

var file_Sleepy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Sleepy_proto_goTypes = []any{
	(*Device)(nil),           // 0: proto.Device
	(*RegisterResponse)(nil), // 1: proto.RegisterResponse
	(*State)(nil),            // 2: proto.State
	(*Empty)(nil),            // 3: proto.Empty
}
var file_Sleepy_proto_depIdxs = []int32{
	0, // 0: proto.Sleepy.RegisterDevice:input_type -> proto.Device
	3, // 1: proto.Sleepy.Unregister:input_type -> proto.Empty
	2, // 2: proto.Sleepy.ReportDeviceState:input_type -> proto.State
	1, // 3: proto.Sleepy.RegisterDevice:output_type -> proto.RegisterResponse
	3, // 4: proto.Sleepy.Unregister:output_type -> proto.Empty
	3, // 5: proto.Sleepy.ReportDeviceState:output_type -> proto.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Sleepy_proto_init() }
func file_Sleepy_proto_init() {
	if File_Sleepy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Sleepy_proto_rawDesc), len(file_Sleepy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Sleepy_proto_goTypes,
		DependencyIndexes: file_Sleepy_proto_depIdxs,
		MessageInfos:      file_Sleepy_proto_msgTypes,
	}.Build()
	File_Sleepy_proto = out.File
	file_Sleepy_proto_goTypes = nil
	file_Sleepy_proto_depIdxs = nil
}
